version: "3.8"

services:
  backend:
    build: ./Backend
    container_name: "backend"
    depends_on:
      rabbitmq:
        condition: service_healthy
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGO_URI=
      - JWT_SECRET=
      - NODE_ENV=production
      - UPSTASH_REDIS_REST_URL=
      - UPSTASH_REDIS_REST_TOKEN=
      - RABBITMQ_URL=
    networks:
      - app-network
  notificationservice:
    build: ./NotificationService
    container_name: "notificationservice"
    depends_on:
      rabbitmq:
        condition: service_healthy
    ports:
      - "4002:4002"
    env_file:
      - ./NotificationService/.env
    networks:
      - app-network
  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: "rabbitmq"
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 5s
      timeout: 10s
      retries: 5
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=
      - RABBITMQ_DEFAULT_PASS=
    networks:
      - app-network
networks:
  app-network:
    driver: bridge